<?php

namespace Database\Seeders;

use App\Models\Division;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class LocationSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $divisions = array(
            array('id' => '1','name' => 'চট্টগ্রাম','created_at' => NULL,'updated_at' => NULL),
            array('id' => '2','name' => 'রাজশাহী','created_at' => NULL,'updated_at' => NULL),
            array('id' => '3','name' => 'খুলনা','created_at' => NULL,'updated_at' => NULL),
            array('id' => '4','name' => 'বরিশাল','created_at' => NULL,'updated_at' => NULL),
            array('id' => '5','name' => 'সিলেট','created_at' => NULL,'updated_at' => NULL),
            array('id' => '6','name' => 'ঢাকা','created_at' => NULL,'updated_at' => NULL),
            array('id' => '7','name' => 'রংপুর','created_at' => NULL,'updated_at' => NULL),
            array('id' => '8','name' => 'ময়মনসিংহ','created_at' => NULL,'updated_at' => NULL)
          );

        $districts = array(
            array('id' => '1','name' => 'কুমিল্লা','division_id' => '1'),
            array('id' => '2','name' => 'ফেনী','division_id' => '1'),
            array('id' => '3','name' => 'ব্রাহ্মণবাড়িয়া','division_id' => '1'),
            array('id' => '4','name' => 'রাঙ্গামাটি','division_id' => '1'),
            array('id' => '5','name' => 'নোয়াখালী','division_id' => '1'),
            array('id' => '6','name' => 'চাঁদপুর','division_id' => '1'),
            array('id' => '7','name' => 'লক্ষ্মীপুর','division_id' => '1'),
            array('id' => '8','name' => 'চট্টগ্রাম','division_id' => '1'),
            array('id' => '9','name' => 'কক্সবাজার','division_id' => '1'),
            array('id' => '10','name' => 'খাগড়াছড়ি','division_id' => '1'),
            array('id' => '11','name' => 'বান্দরবান','division_id' => '1'),
            array('id' => '12','name' => 'সিরাজগঞ্জ','division_id' => '2'),
            array('id' => '13','name' => 'পাবনা','division_id' => '2'),
            array('id' => '14','name' => 'বগুড়া','division_id' => '2'),
            array('id' => '15','name' => 'রাজশাহী','division_id' => '2'),
            array('id' => '16','name' => 'নাটোর','division_id' => '2'),
            array('id' => '17','name' => 'জয়পুরহাট','division_id' => '2'),
            array('id' => '18','name' => 'চাঁপাইনবাবগঞ্জ','division_id' => '2'),
            array('id' => '19','name' => 'নওগাঁ','division_id' => '2'),
            array('id' => '20','name' => 'যশোর','division_id' => '3'),
            array('id' => '21','name' => 'সাতক্ষীরা','division_id' => '3'),
            array('id' => '22','name' => 'মেহেরপুর','division_id' => '3'),
            array('id' => '23','name' => 'নড়াইল','division_id' => '3'),
            array('id' => '24','name' => 'চুয়াডাঙ্গা','division_id' => '3'),
            array('id' => '25','name' => 'কুষ্টিয়া','division_id' => '3'),
            array('id' => '26','name' => 'মাগুরা','division_id' => '3'),
            array('id' => '27','name' => 'খুলনা','division_id' => '3'),
            array('id' => '28','name' => 'বাগেরহাট','division_id' => '3'),
            array('id' => '29','name' => 'ঝিনাইদহ','division_id' => '3'),
            array('id' => '30','name' => 'ঝালকাঠি','division_id' => '4'),
            array('id' => '31','name' => 'পটুয়াখালী','division_id' => '4'),
            array('id' => '32','name' => 'পিরোজপুর','division_id' => '4'),
            array('id' => '33','name' => 'বরিশাল','division_id' => '4'),
            array('id' => '34','name' => 'ভোলা','division_id' => '4'),
            array('id' => '35','name' => 'বরগুনা','division_id' => '4'),
            array('id' => '36','name' => 'সিলেট','division_id' => '5'),
            array('id' => '37','name' => 'মৌলভীবাজার','division_id' => '5'),
            array('id' => '38','name' => 'হবিগঞ্জ','division_id' => '5'),
            array('id' => '39','name' => 'সুনামগঞ্জ','division_id' => '5'),
            array('id' => '40','name' => 'নরসিংদী','division_id' => '6'),
            array('id' => '41','name' => 'গাজীপুর','division_id' => '6'),
            array('id' => '42','name' => 'শরীয়তপুর','division_id' => '6'),
            array('id' => '43','name' => 'নারায়ণগঞ্জ','division_id' => '6'),
            array('id' => '44','name' => 'টাঙ্গাইল','division_id' => '6'),
            array('id' => '45','name' => 'কিশোরগঞ্জ','division_id' => '6'),
            array('id' => '46','name' => 'মানিকগঞ্জ','division_id' => '6'),
            array('id' => '47','name' => 'ঢাকা','division_id' => '6'),
            array('id' => '48','name' => 'মুন্সিগঞ্জ','division_id' => '6'),
            array('id' => '49','name' => 'রাজবাড়ী','division_id' => '6'),
            array('id' => '50','name' => 'মাদারীপুর','division_id' => '6'),
            array('id' => '51','name' => 'গোপালগঞ্জ','division_id' => '6'),
            array('id' => '52','name' => 'ফরিদপুর','division_id' => '6'),
            array('id' => '53','name' => 'পঞ্চগড়','division_id' => '7'),
            array('id' => '54','name' => 'দিনাজপুর','division_id' => '7'),
            array('id' => '55','name' => 'লালমনিরহাট','division_id' => '7'),
            array('id' => '56','name' => 'নীলফামারী','division_id' => '7'),
            array('id' => '57','name' => 'গাইবান্ধা','division_id' => '7'),
            array('id' => '58','name' => 'ঠাকুরগাঁও','division_id' => '7'),
            array('id' => '59','name' => 'রংপুর','division_id' => '7'),
            array('id' => '60','name' => 'কুড়িগ্রাম','division_id' => '7'),
            array('id' => '61','name' => 'শেরপুর','division_id' => '8'),
            array('id' => '62','name' => 'ময়মনসিংহ','division_id' => '8'),
            array('id' => '63','name' => 'জামালপুর','division_id' => '8'),
            array('id' => '64','name' => 'নেত্রকোণা','division_id' => '8')
          );

          $cities = array(
            array('id' => '1','name' => 'দেবিদ্বার','district_id' => '1'),
            array('id' => '2','name' => 'বরুড়া','district_id' => '1'),
            array('id' => '3','name' => 'ব্রাহ্মণপাড়া','district_id' => '1'),
            array('id' => '4','name' => 'চান্দিনা','district_id' => '1'),
            array('id' => '5','name' => 'চৌদ্দগ্রাম','district_id' => '1'),
            array('id' => '6','name' => 'দাউদকান্দি','district_id' => '1'),
            array('id' => '7','name' => 'হোমনা','district_id' => '1'),
            array('id' => '8','name' => 'লাকসাম','district_id' => '1'),
            array('id' => '9','name' => 'মুরাদনগর','district_id' => '1'),
            array('id' => '10','name' => 'নাঙ্গলকোট','district_id' => '1'),
            array('id' => '11','name' => 'কুমিল্লা সদর','district_id' => '1'),
            array('id' => '12','name' => 'মেঘনা','district_id' => '1'),
            array('id' => '13','name' => 'মনোহরগঞ্জ','district_id' => '1'),
            array('id' => '14','name' => 'সদর দক্ষিণ','district_id' => '1'),
            array('id' => '15','name' => 'তিতাস','district_id' => '1'),
            array('id' => '16','name' => 'বুড়িচং','district_id' => '1'),
            array('id' => '17','name' => 'লালমাই','district_id' => '1'),
            array('id' => '18','name' => 'ছাগলনাইয়া','district_id' => '2'),
            array('id' => '19','name' => 'ফেনী সদর','district_id' => '2'),
            array('id' => '20','name' => 'সোনাগাজী','district_id' => '2'),
            array('id' => '21','name' => 'ফুলগাজী','district_id' => '2'),
            array('id' => '22','name' => 'পরশুরাম','district_id' => '2'),
            array('id' => '23','name' => 'দাগনভূঞা','district_id' => '2'),
            array('id' => '24','name' => 'ব্রাহ্মণবাড়িয়া সদর','district_id' => '3'),
            array('id' => '25','name' => 'কসবা','district_id' => '3'),
            array('id' => '26','name' => 'নাসিরনগর','district_id' => '3'),
            array('id' => '27','name' => 'সরাইল','district_id' => '3'),
            array('id' => '28','name' => 'আশুগঞ্জ','district_id' => '3'),
            array('id' => '29','name' => 'আখাউড়া','district_id' => '3'),
            array('id' => '30','name' => 'নবীনগর','district_id' => '3'),
            array('id' => '31','name' => 'বাঞ্ছারামপুর','district_id' => '3'),
            array('id' => '32','name' => 'বিজয়নগর','district_id' => '3'),
            array('id' => '33','name' => 'রাঙ্গামাটি সদর','district_id' => '4'),
            array('id' => '34','name' => 'কাপ্তাই','district_id' => '4'),
            array('id' => '35','name' => 'কাউখালী','district_id' => '4'),
            array('id' => '36','name' => 'বাঘাইছড়ি','district_id' => '4'),
            array('id' => '37','name' => 'বরকল','district_id' => '4'),
            array('id' => '38','name' => 'লংগদু','district_id' => '4'),
            array('id' => '39','name' => 'রাজস্থলী','district_id' => '4'),
            array('id' => '40','name' => 'বিলাইছড়ি','district_id' => '4'),
            array('id' => '41','name' => 'জুরাছড়ি','district_id' => '4'),
            array('id' => '42','name' => 'নানিয়ারচর','district_id' => '4'),
            array('id' => '43','name' => 'নোয়াখালী সদর','district_id' => '5'),
            array('id' => '44','name' => 'কোম্পানীগঞ্জ','district_id' => '5'),
            array('id' => '45','name' => 'বেগমগঞ্জ','district_id' => '5'),
            array('id' => '46','name' => 'হাতিয়া','district_id' => '5'),
            array('id' => '47','name' => 'সুবর্ণচর','district_id' => '5'),
            array('id' => '48','name' => 'কবিরহাট','district_id' => '5'),
            array('id' => '49','name' => 'সেনবাগ','district_id' => '5'),
            array('id' => '50','name' => 'চাটখিল','district_id' => '5'),
            array('id' => '51','name' => 'সোনাইমুড়ী','district_id' => '5'),
            array('id' => '52','name' => 'হাইমচর','district_id' => '6'),
            array('id' => '53','name' => 'কচুয়া','district_id' => '6'),
            array('id' => '54','name' => 'শাহরাস্তি	','district_id' => '6'),
            array('id' => '55','name' => 'চাঁদপুর সদর','district_id' => '6'),
            array('id' => '56','name' => 'মতলব দক্ষিণ','district_id' => '6'),
            array('id' => '57','name' => 'হাজীগঞ্জ','district_id' => '6'),
            array('id' => '58','name' => 'মতলব উত্তর','district_id' => '6'),
            array('id' => '59','name' => 'ফরিদগঞ্জ','district_id' => '6'),
            array('id' => '60','name' => 'লক্ষ্মীপুর সদর','district_id' => '7'),
            array('id' => '61','name' => 'কমলনগর','district_id' => '7'),
            array('id' => '62','name' => 'রায়পুর','district_id' => '7'),
            array('id' => '63','name' => 'রামগতি','district_id' => '7'),
            array('id' => '64','name' => 'রামগঞ্জ','district_id' => '7'),
            array('id' => '65','name' => 'রাঙ্গুনিয়া','district_id' => '8'),
            array('id' => '66','name' => 'সীতাকুন্ড','district_id' => '8'),
            array('id' => '67','name' => 'মীরসরাই','district_id' => '8'),
            array('id' => '68','name' => 'পটিয়া','district_id' => '8'),
            array('id' => '69','name' => 'সন্দ্বীপ','district_id' => '8'),
            array('id' => '70','name' => 'বাঁশখালী','district_id' => '8'),
            array('id' => '71','name' => 'বোয়ালখালী','district_id' => '8'),
            array('id' => '72','name' => 'আনোয়ারা','district_id' => '8'),
            array('id' => '73','name' => 'চন্দনাইশ','district_id' => '8'),
            array('id' => '74','name' => 'সাতকানিয়া','district_id' => '8'),
            array('id' => '75','name' => 'লোহাগাড়া','district_id' => '8'),
            array('id' => '76','name' => 'হাটহাজারী','district_id' => '8'),
            array('id' => '77','name' => 'ফটিকছড়ি','district_id' => '8'),
            array('id' => '78','name' => 'রাউজান','district_id' => '8'),
            array('id' => '79','name' => 'কর্ণফুলী','district_id' => '8'),
            array('id' => '80','name' => 'কক্সবাজার সদর','district_id' => '9'),
            array('id' => '81','name' => 'চকরিয়া','district_id' => '9'),
            array('id' => '82','name' => 'কুতুবদিয়া','district_id' => '9'),
            array('id' => '83','name' => 'উখিয়া','district_id' => '9'),
            array('id' => '84','name' => 'মহেশখালী','district_id' => '9'),
            array('id' => '85','name' => 'পেকুয়া','district_id' => '9'),
            array('id' => '86','name' => 'রামু','district_id' => '9'),
            array('id' => '87','name' => 'টেকনাফ','district_id' => '9'),
            array('id' => '88','name' => 'খাগড়াছড়ি সদর','district_id' => '10'),
            array('id' => '89','name' => 'দিঘীনালা','district_id' => '10'),
            array('id' => '90','name' => 'পানছড়ি','district_id' => '10'),
            array('id' => '91','name' => 'লক্ষীছড়ি','district_id' => '10'),
            array('id' => '92','name' => 'মহালছড়ি','district_id' => '10'),
            array('id' => '93','name' => 'মানিকছড়ি','district_id' => '10'),
            array('id' => '94','name' => 'রামগড়','district_id' => '10'),
            array('id' => '95','name' => 'মাটিরাঙ্গা','district_id' => '10'),
            array('id' => '96','name' => 'গুইমারা','district_id' => '10'),
            array('id' => '97','name' => 'বান্দরবান সদর','district_id' => '11'),
            array('id' => '98','name' => 'আলীকদম','district_id' => '11'),
            array('id' => '99','name' => 'নাইক্ষ্যংছড়ি','district_id' => '11'),
            array('id' => '100','name' => 'রোয়াংছড়ি','district_id' => '11'),
            array('id' => '101','name' => 'লামা','district_id' => '11'),
            array('id' => '102','name' => 'রুমা','district_id' => '11'),
            array('id' => '103','name' => 'থানচি','district_id' => '11'),
            array('id' => '104','name' => 'বেলকুচি','district_id' => '12'),
            array('id' => '105','name' => 'চৌহালি','district_id' => '12'),
            array('id' => '106','name' => 'কামারখন্দ','district_id' => '12'),
            array('id' => '107','name' => 'কাজীপুর','district_id' => '12'),
            array('id' => '108','name' => 'রায়গঞ্জ','district_id' => '12'),
            array('id' => '109','name' => 'শাহজাদপুর','district_id' => '12'),
            array('id' => '110','name' => 'সিরাজগঞ্জ সদর','district_id' => '12'),
            array('id' => '111','name' => 'তাড়াশ','district_id' => '12'),
            array('id' => '112','name' => 'উল্লাপাড়া','district_id' => '12'),
            array('id' => '113','name' => 'সুজানগর','district_id' => '13'),
            array('id' => '114','name' => 'ঈশ্বরদী','district_id' => '13'),
            array('id' => '115','name' => 'ভাঙ্গুড়া','district_id' => '13'),
            array('id' => '116','name' => 'পাবনা সদর','district_id' => '13'),
            array('id' => '117','name' => 'বেড়া','district_id' => '13'),
            array('id' => '118','name' => 'আটঘরিয়া','district_id' => '13'),
            array('id' => '119','name' => 'চাটমোহর','district_id' => '13'),
            array('id' => '120','name' => 'সাঁথিয়া','district_id' => '13'),
            array('id' => '121','name' => 'ফরিদপুর','district_id' => '13'),
            array('id' => '122','name' => 'কাহালু','district_id' => '14'),
            array('id' => '123','name' => 'বগুড়া সদর','district_id' => '14'),
            array('id' => '124','name' => 'সারিয়াকান্দি','district_id' => '14'),
            array('id' => '125','name' => 'শাজাহানপুর','district_id' => '14'),
            array('id' => '126','name' => 'দুপচাচিঁয়া','district_id' => '14'),
            array('id' => '127','name' => 'আদমদিঘি','district_id' => '14'),
            array('id' => '128','name' => 'নন্দিগ্রাম','district_id' => '14'),
            array('id' => '129','name' => 'সোনাতলা','district_id' => '14'),
            array('id' => '130','name' => 'ধুনট','district_id' => '14'),
            array('id' => '131','name' => 'গাবতলী','district_id' => '14'),
            array('id' => '132','name' => 'শেরপুর','district_id' => '14'),
            array('id' => '133','name' => 'শিবগঞ্জ','district_id' => '14'),
            array('id' => '134','name' => 'পবা','district_id' => '15'),
            array('id' => '135','name' => 'দুর্গাপুর','district_id' => '15'),
            array('id' => '136','name' => 'মোহনপুর','district_id' => '15'),
            array('id' => '137','name' => 'চারঘাট','district_id' => '15'),
            array('id' => '138','name' => 'পুঠিয়া','district_id' => '15'),
            array('id' => '139','name' => 'বাঘা','district_id' => '15'),
            array('id' => '140','name' => 'গোদাগাড়ী','district_id' => '15'),
            array('id' => '141','name' => 'তানোর','district_id' => '15'),
            array('id' => '142','name' => 'বাগমারা','district_id' => '15'),
            array('id' => '143','name' => 'নাটোর সদর','district_id' => '16'),
            array('id' => '144','name' => 'সিংড়া','district_id' => '16'),
            array('id' => '145','name' => 'বড়াইগ্রাম','district_id' => '16'),
            array('id' => '146','name' => 'বাগাতিপাড়া','district_id' => '16'),
            array('id' => '147','name' => 'লালপুর','district_id' => '16'),
            array('id' => '148','name' => 'গুরুদাসপুর','district_id' => '16'),
            array('id' => '149','name' => 'নলডাঙ্গা','district_id' => '16'),
            array('id' => '150','name' => 'আক্কেলপুর','district_id' => '17'),
            array('id' => '151','name' => 'কালাই','district_id' => '17'),
            array('id' => '152','name' => 'ক্ষেতলাল','district_id' => '17'),
            array('id' => '153','name' => 'পাঁচবিবি','district_id' => '17'),
            array('id' => '154','name' => 'জয়পুরহাট সদর','district_id' => '17'),
            array('id' => '155','name' => 'চাঁপাইনবাবগঞ্জ সদর','district_id' => '18'),
            array('id' => '156','name' => 'গোমস্তাপুর','district_id' => '18'),
            array('id' => '157','name' => 'নাচোল','district_id' => '18'),
            array('id' => '158','name' => 'ভোলাহাট','district_id' => '18'),
            array('id' => '159','name' => 'শিবগঞ্জ','district_id' => '18'),
            array('id' => '160','name' => 'মহাদেবপুর','district_id' => '19'),
            array('id' => '161','name' => 'বদলগাছী','district_id' => '19'),
            array('id' => '162','name' => 'পত্নিতলা','district_id' => '19'),
            array('id' => '163','name' => 'ধামইরহাট','district_id' => '19'),
            array('id' => '164','name' => 'নিয়ামতপুর','district_id' => '19'),
            array('id' => '165','name' => 'মান্দা','district_id' => '19'),
            array('id' => '166','name' => 'আত্রাই','district_id' => '19'),
            array('id' => '167','name' => 'রাণীনগর','district_id' => '19'),
            array('id' => '168','name' => 'নওগাঁ সদর','district_id' => '19'),
            array('id' => '169','name' => 'পোরশা','district_id' => '19'),
            array('id' => '170','name' => 'সাপাহার','district_id' => '19'),
            array('id' => '171','name' => 'মণিরামপুর','district_id' => '20'),
            array('id' => '172','name' => 'অভয়নগর','district_id' => '20'),
            array('id' => '173','name' => 'বাঘারপাড়া','district_id' => '20'),
            array('id' => '174','name' => 'চৌগাছা','district_id' => '20'),
            array('id' => '175','name' => 'ঝিকরগাছা','district_id' => '20'),
            array('id' => '176','name' => 'কেশবপুর','district_id' => '20'),
            array('id' => '177','name' => 'যশোর সদর','district_id' => '20'),
            array('id' => '178','name' => 'শার্শা','district_id' => '20'),
            array('id' => '179','name' => 'আশাশুনি','district_id' => '21'),
            array('id' => '180','name' => 'দেবহাটা','district_id' => '21'),
            array('id' => '181','name' => 'কলারোয়া','district_id' => '21'),
            array('id' => '182','name' => 'সাতক্ষীরা সদর','district_id' => '21'),
            array('id' => '183','name' => 'শ্যামনগর','district_id' => '21'),
            array('id' => '184','name' => 'তালা','district_id' => '21'),
            array('id' => '185','name' => 'কালিগঞ্জ','district_id' => '21'),
            array('id' => '186','name' => 'মুজিবনগর','district_id' => '22'),
            array('id' => '187','name' => 'মেহেরপুর সদর','district_id' => '22'),
            array('id' => '188','name' => 'গাংনী','district_id' => '22'),
            array('id' => '189','name' => 'নড়াইল সদর','district_id' => '23'),
            array('id' => '190','name' => 'লোহাগড়া','district_id' => '23'),
            array('id' => '191','name' => 'কালিয়া','district_id' => '23'),
            array('id' => '192','name' => 'চুয়াডাঙ্গা সদর','district_id' => '24'),
            array('id' => '193','name' => 'আলমডাঙ্গা','district_id' => '24'),
            array('id' => '194','name' => 'দামুড়হুদা','district_id' => '24'),
            array('id' => '195','name' => 'জীবননগর','district_id' => '24'),
            array('id' => '196','name' => 'কুষ্টিয়া সদর','district_id' => '25'),
            array('id' => '197','name' => 'কুমারখালী','district_id' => '25'),
            array('id' => '198','name' => 'খোকসা','district_id' => '25'),
            array('id' => '199','name' => 'মিরপুর','district_id' => '25'),
            array('id' => '200','name' => 'দৌলতপুর','district_id' => '25'),
            array('id' => '201','name' => 'ভেড়ামারা','district_id' => '25'),
            array('id' => '202','name' => 'শালিখা','district_id' => '26'),
            array('id' => '203','name' => 'শ্রীপুর','district_id' => '26'),
            array('id' => '204','name' => 'মাগুরা সদর','district_id' => '26'),
            array('id' => '205','name' => 'মহম্মদপুর','district_id' => '26'),
            array('id' => '206','name' => 'পাইকগাছা','district_id' => '27'),
            array('id' => '207','name' => 'ফুলতলা','district_id' => '27'),
            array('id' => '208','name' => 'দিঘলিয়া','district_id' => '27'),
            array('id' => '209','name' => 'রূপসা','district_id' => '27'),
            array('id' => '210','name' => 'তেরখাদা','district_id' => '27'),
            array('id' => '211','name' => 'ডুমুরিয়া','district_id' => '27'),
            array('id' => '212','name' => 'বটিয়াঘাটা','district_id' => '27'),
            array('id' => '213','name' => 'দাকোপ','district_id' => '27'),
            array('id' => '214','name' => 'কয়রা','district_id' => '27'),
            array('id' => '215','name' => 'ফকিরহাট','district_id' => '28'),
            array('id' => '216','name' => 'বাগেরহাট সদর','district_id' => '28'),
            array('id' => '217','name' => 'মোল্লাহাট','district_id' => '28'),
            array('id' => '218','name' => 'শরণখোলা','district_id' => '28'),
            array('id' => '219','name' => 'রামপাল','district_id' => '28'),
            array('id' => '220','name' => 'মোড়েলগঞ্জ','district_id' => '28'),
            array('id' => '221','name' => 'কচুয়া','district_id' => '28'),
            array('id' => '222','name' => 'মোংলা','district_id' => '28'),
            array('id' => '223','name' => 'চিতলমারী','district_id' => '28'),
            array('id' => '224','name' => 'ঝিনাইদহ সদর','district_id' => '29'),
            array('id' => '225','name' => 'শৈলকুপা','district_id' => '29'),
            array('id' => '226','name' => 'হরিণাকুন্ডু','district_id' => '29'),
            array('id' => '227','name' => 'কালীগঞ্জ','district_id' => '29'),
            array('id' => '228','name' => 'কোটচাঁদপুর','district_id' => '29'),
            array('id' => '229','name' => 'মহেশপুর','district_id' => '29'),
            array('id' => '230','name' => 'ঝালকাঠি সদর','district_id' => '30'),
            array('id' => '231','name' => 'কাঠালিয়া','district_id' => '30'),
            array('id' => '232','name' => 'নলছিটি','district_id' => '30'),
            array('id' => '233','name' => 'রাজাপুর','district_id' => '30'),
            array('id' => '234','name' => 'বাউফল','district_id' => '31'),
            array('id' => '235','name' => 'পটুয়াখালী সদর','district_id' => '31'),
            array('id' => '236','name' => 'দুমকি','district_id' => '31'),
            array('id' => '237','name' => 'দশমিনা','district_id' => '31'),
            array('id' => '238','name' => 'কলাপাড়া','district_id' => '31'),
            array('id' => '239','name' => 'মির্জাগঞ্জ','district_id' => '31'),
            array('id' => '240','name' => 'গলাচিপা','district_id' => '31'),
            array('id' => '241','name' => 'রাঙ্গাবালী','district_id' => '31'),
            array('id' => '242','name' => 'পিরোজপুর সদর','district_id' => '32'),
            array('id' => '243','name' => 'নাজিরপুর','district_id' => '32'),
            array('id' => '244','name' => 'কাউখালী','district_id' => '32'),
            array('id' => '245','name' => 'জিয়ানগর','district_id' => '32'),
            array('id' => '246','name' => 'ভান্ডারিয়া','district_id' => '32'),
            array('id' => '247','name' => 'মঠবাড়ীয়া','district_id' => '32'),
            array('id' => '248','name' => 'নেছারাবাদ','district_id' => '32'),
            array('id' => '249','name' => 'বরিশাল সদর','district_id' => '33'),
            array('id' => '250','name' => 'বাকেরগঞ্জ','district_id' => '33'),
            array('id' => '251','name' => 'বাবুগঞ্জ','district_id' => '33'),
            array('id' => '252','name' => 'উজিরপুর','district_id' => '33'),
            array('id' => '253','name' => 'বানারীপাড়া','district_id' => '33'),
            array('id' => '254','name' => 'গৌরনদী','district_id' => '33'),
            array('id' => '255','name' => 'আগৈলঝাড়া','district_id' => '33'),
            array('id' => '256','name' => 'মেহেন্দিগঞ্জ','district_id' => '33'),
            array('id' => '257','name' => 'মুলাদী','district_id' => '33'),
            array('id' => '258','name' => 'হিজলা','district_id' => '33'),
            array('id' => '259','name' => 'ভোলা সদর','district_id' => '34'),
            array('id' => '260','name' => 'বোরহান উদ্দিন','district_id' => '34'),
            array('id' => '261','name' => 'চরফ্যাশন','district_id' => '34'),
            array('id' => '262','name' => 'দৌলতখান','district_id' => '34'),
            array('id' => '263','name' => 'মনপুরা','district_id' => '34'),
            array('id' => '264','name' => 'তজুমদ্দিন','district_id' => '34'),
            array('id' => '265','name' => 'লালমোহন','district_id' => '34'),
            array('id' => '266','name' => 'আমতলী','district_id' => '35'),
            array('id' => '267','name' => 'বরগুনা সদর','district_id' => '35'),
            array('id' => '268','name' => 'বেতাগী','district_id' => '35'),
            array('id' => '269','name' => 'বামনা','district_id' => '35'),
            array('id' => '270','name' => 'পাথরঘাটা','district_id' => '35'),
            array('id' => '271','name' => 'তালতলি','district_id' => '35'),
            array('id' => '272','name' => 'বালাগঞ্জ','district_id' => '36'),
            array('id' => '273','name' => 'বিয়ানীবাজার','district_id' => '36'),
            array('id' => '274','name' => 'বিশ্বনাথ','district_id' => '36'),
            array('id' => '275','name' => 'কোম্পানীগঞ্জ','district_id' => '36'),
            array('id' => '276','name' => 'ফেঞ্চুগঞ্জ','district_id' => '36'),
            array('id' => '277','name' => 'গোলাপগঞ্জ','district_id' => '36'),
            array('id' => '278','name' => 'গোয়াইনঘাট','district_id' => '36'),
            array('id' => '279','name' => 'জৈন্তাপুর','district_id' => '36'),
            array('id' => '280','name' => 'কানাইঘাট','district_id' => '36'),
            array('id' => '281','name' => 'সিলেট সদর','district_id' => '36'),
            array('id' => '282','name' => 'জকিগঞ্জ','district_id' => '36'),
            array('id' => '283','name' => 'দক্ষিণ সুরমা','district_id' => '36'),
            array('id' => '284','name' => 'ওসমানী নগর','district_id' => '36'),
            array('id' => '285','name' => 'বড়লেখা','district_id' => '37'),
            array('id' => '286','name' => 'কমলগঞ্জ','district_id' => '37'),
            array('id' => '287','name' => 'কুলাউড়া','district_id' => '37'),
            array('id' => '288','name' => 'মৌলভীবাজার সদর','district_id' => '37'),
            array('id' => '289','name' => 'রাজনগর','district_id' => '37'),
            array('id' => '290','name' => 'শ্রীমঙ্গল','district_id' => '37'),
            array('id' => '291','name' => 'জুড়ী','district_id' => '37'),
            array('id' => '292','name' => 'নবীগঞ্জ','district_id' => '38'),
            array('id' => '293','name' => 'বাহুবল','district_id' => '38'),
            array('id' => '294','name' => 'আজমিরীগঞ্জ','district_id' => '38'),
            array('id' => '295','name' => 'বানিয়াচং','district_id' => '38'),
            array('id' => '296','name' => 'লাখাই','district_id' => '38'),
            array('id' => '297','name' => 'চুনারুঘাট','district_id' => '38'),
            array('id' => '298','name' => 'হবিগঞ্জ সদর','district_id' => '38'),
            array('id' => '299','name' => 'মাধবপুর','district_id' => '38'),
            array('id' => '300','name' => 'সুনামগঞ্জ সদর','district_id' => '39'),
            array('id' => '301','name' => 'দক্ষিণ সুনামগঞ্জ','district_id' => '39'),
            array('id' => '302','name' => 'বিশ্বম্ভরপুর','district_id' => '39'),
            array('id' => '303','name' => 'ছাতক','district_id' => '39'),
            array('id' => '304','name' => 'জগন্নাথপুর','district_id' => '39'),
            array('id' => '305','name' => 'দোয়ারাবাজার','district_id' => '39'),
            array('id' => '306','name' => 'তাহিরপুর','district_id' => '39'),
            array('id' => '307','name' => 'ধর্মপাশা','district_id' => '39'),
            array('id' => '308','name' => 'জামালগঞ্জ','district_id' => '39'),
            array('id' => '309','name' => 'শাল্লা','district_id' => '39'),
            array('id' => '310','name' => 'দিরাই','district_id' => '39'),
            array('id' => '311','name' => 'বেলাবো','district_id' => '40'),
            array('id' => '312','name' => 'মনোহরদী','district_id' => '40'),
            array('id' => '313','name' => 'নরসিংদী সদর','district_id' => '40'),
            array('id' => '314','name' => 'পলাশ','district_id' => '40'),
            array('id' => '315','name' => 'রায়পুরা','district_id' => '40'),
            array('id' => '316','name' => 'শিবপুর','district_id' => '40'),
            array('id' => '317','name' => 'কালীগঞ্জ','district_id' => '41'),
            array('id' => '318','name' => 'কালিয়াকৈর','district_id' => '41'),
            array('id' => '319','name' => 'কাপাসিয়া','district_id' => '41'),
            array('id' => '320','name' => 'গাজীপুর সদর','district_id' => '41'),
            array('id' => '321','name' => 'শ্রীপুর','district_id' => '41'),
            array('id' => '322','name' => 'শরিয়তপুর সদর','district_id' => '42'),
            array('id' => '323','name' => 'নড়িয়া','district_id' => '42'),
            array('id' => '324','name' => 'জাজিরা','district_id' => '42'),
            array('id' => '325','name' => 'গোসাইরহাট','district_id' => '42'),
            array('id' => '326','name' => 'ভেদরগঞ্জ','district_id' => '42'),
            array('id' => '327','name' => 'ডামুড্যা','district_id' => '42'),
            array('id' => '328','name' => 'আড়াইহাজার','district_id' => '43'),
            array('id' => '329','name' => 'বন্দর','district_id' => '43'),
            array('id' => '330','name' => 'নারায়নগঞ্জ সদর','district_id' => '43'),
            array('id' => '331','name' => 'রূপগঞ্জ','district_id' => '43'),
            array('id' => '332','name' => 'সোনারগাঁ','district_id' => '43'),
            array('id' => '333','name' => 'বাসাইল','district_id' => '44'),
            array('id' => '334','name' => 'ভুয়াপুর','district_id' => '44'),
            array('id' => '335','name' => 'দেলদুয়ার','district_id' => '44'),
            array('id' => '336','name' => 'ঘাটাইল','district_id' => '44'),
            array('id' => '337','name' => 'গোপালপুর','district_id' => '44'),
            array('id' => '338','name' => 'মধুপুর','district_id' => '44'),
            array('id' => '339','name' => 'মির্জাপুর','district_id' => '44'),
            array('id' => '340','name' => 'নাগরপুর','district_id' => '44'),
            array('id' => '341','name' => 'সখিপুর','district_id' => '44'),
            array('id' => '342','name' => 'টাঙ্গাইল সদর','district_id' => '44'),
            array('id' => '343','name' => 'কালিহাতী','district_id' => '44'),
            array('id' => '344','name' => 'ধনবাড়ী','district_id' => '44'),
            array('id' => '345','name' => 'ইটনা','district_id' => '45'),
            array('id' => '346','name' => 'কটিয়াদী','district_id' => '45'),
            array('id' => '347','name' => 'ভৈরব','district_id' => '45'),
            array('id' => '348','name' => 'তাড়াইল','district_id' => '45'),
            array('id' => '349','name' => 'হোসেনপুর','district_id' => '45'),
            array('id' => '350','name' => 'পাকুন্দিয়া','district_id' => '45'),
            array('id' => '351','name' => 'কুলিয়ারচর','district_id' => '45'),
            array('id' => '352','name' => 'কিশোরগঞ্জ সদর','district_id' => '45'),
            array('id' => '353','name' => 'করিমগঞ্জ','district_id' => '45'),
            array('id' => '354','name' => 'বাজিতপুর','district_id' => '45'),
            array('id' => '355','name' => 'অষ্টগ্রাম','district_id' => '45'),
            array('id' => '356','name' => 'মিঠামইন','district_id' => '45'),
            array('id' => '357','name' => 'নিকলী','district_id' => '45'),
            array('id' => '358','name' => 'হরিরামপুর','district_id' => '46'),
            array('id' => '359','name' => 'সাটুরিয়া','district_id' => '46'),
            array('id' => '360','name' => 'মানিকগঞ্জ সদর','district_id' => '46'),
            array('id' => '361','name' => 'ঘিওর','district_id' => '46'),
            array('id' => '362','name' => 'শিবালয়','district_id' => '46'),
            array('id' => '363','name' => 'দৌলতপুর','district_id' => '46'),
            array('id' => '364','name' => 'সিংগাইর','district_id' => '46'),
            array('id' => '365','name' => 'সাভার','district_id' => '47'),
            array('id' => '366','name' => 'ধামরাই','district_id' => '47'),
            array('id' => '367','name' => 'কেরাণীগঞ্জ','district_id' => '47'),
            array('id' => '368','name' => 'নবাবগঞ্জ','district_id' => '47'),
            array('id' => '369','name' => 'দোহার','district_id' => '47'),
            array('id' => '370','name' => 'মুন্সিগঞ্জ সদর','district_id' => '48'),
            array('id' => '371','name' => 'শ্রীনগর','district_id' => '48'),
            array('id' => '372','name' => 'সিরাজদিখান','district_id' => '48'),
            array('id' => '373','name' => 'লৌহজং','district_id' => '48'),
            array('id' => '374','name' => 'গজারিয়া','district_id' => '48'),
            array('id' => '375','name' => 'টংগীবাড়ি','district_id' => '48'),
            array('id' => '376','name' => 'রাজবাড়ী সদর','district_id' => '49'),
            array('id' => '377','name' => 'গোয়ালন্দ','district_id' => '49'),
            array('id' => '378','name' => 'পাংশা','district_id' => '49'),
            array('id' => '379','name' => 'বালিয়াকান্দি','district_id' => '49'),
            array('id' => '380','name' => 'কালুখালী','district_id' => '49'),
            array('id' => '381','name' => 'মাদারীপুর সদর','district_id' => '50'),
            array('id' => '382','name' => 'শিবচর','district_id' => '50'),
            array('id' => '383','name' => 'কালকিনি','district_id' => '50'),
            array('id' => '384','name' => 'রাজৈর','district_id' => '50'),
            array('id' => '385','name' => 'গোপালগঞ্জ সদর','district_id' => '51'),
            array('id' => '386','name' => 'কাশিয়ানী','district_id' => '51'),
            array('id' => '387','name' => 'টুংগীপাড়া','district_id' => '51'),
            array('id' => '388','name' => 'কোটালীপাড়া','district_id' => '51'),
            array('id' => '389','name' => 'মুকসুদপুর','district_id' => '51'),
            array('id' => '390','name' => 'ফরিদপুর সদর','district_id' => '52'),
            array('id' => '391','name' => 'আলফাডাঙ্গা','district_id' => '52'),
            array('id' => '392','name' => 'বোয়ালমারী','district_id' => '52'),
            array('id' => '393','name' => 'সদরপুর','district_id' => '52'),
            array('id' => '394','name' => 'নগরকান্দা','district_id' => '52'),
            array('id' => '395','name' => 'ভাঙ্গা','district_id' => '52'),
            array('id' => '396','name' => 'চরভদ্রাসন','district_id' => '52'),
            array('id' => '397','name' => 'মধুখালী','district_id' => '52'),
            array('id' => '398','name' => 'সালথা','district_id' => '52'),
            array('id' => '399','name' => 'পঞ্চগড় সদর','district_id' => '53'),
            array('id' => '400','name' => 'দেবীগঞ্জ','district_id' => '53'),
            array('id' => '401','name' => 'বোদা','district_id' => '53'),
            array('id' => '402','name' => 'আটোয়ারী','district_id' => '53'),
            array('id' => '403','name' => 'তেতুলিয়া','district_id' => '53'),
            array('id' => '404','name' => 'নবাবগঞ্জ','district_id' => '54'),
            array('id' => '405','name' => 'বীরগঞ্জ','district_id' => '54'),
            array('id' => '406','name' => 'ঘোড়াঘাট','district_id' => '54'),
            array('id' => '407','name' => 'বিরামপুর','district_id' => '54'),
            array('id' => '408','name' => 'পার্বতীপুর','district_id' => '54'),
            array('id' => '409','name' => 'বোচাগঞ্জ','district_id' => '54'),
            array('id' => '410','name' => 'কাহারোল','district_id' => '54'),
            array('id' => '411','name' => 'ফুলবাড়ী','district_id' => '54'),
            array('id' => '412','name' => 'দিনাজপুর সদর','district_id' => '54'),
            array('id' => '413','name' => 'হাকিমপুর','district_id' => '54'),
            array('id' => '414','name' => 'খানসামা','district_id' => '54'),
            array('id' => '415','name' => 'বিরল','district_id' => '54'),
            array('id' => '416','name' => 'চিরিরবন্দর','district_id' => '54'),
            array('id' => '417','name' => 'লালমনিরহাট সদর','district_id' => '55'),
            array('id' => '418','name' => 'কালীগঞ্জ','district_id' => '55'),
            array('id' => '419','name' => 'হাতীবান্ধা','district_id' => '55'),
            array('id' => '420','name' => 'পাটগ্রাম','district_id' => '55'),
            array('id' => '421','name' => 'আদিতমারী','district_id' => '55'),
            array('id' => '422','name' => 'সৈয়দপুর','district_id' => '56'),
            array('id' => '423','name' => 'ডোমার','district_id' => '56'),
            array('id' => '424','name' => 'ডিমলা','district_id' => '56'),
            array('id' => '425','name' => 'জলঢাকা','district_id' => '56'),
            array('id' => '426','name' => 'কিশোরগঞ্জ','district_id' => '56'),
            array('id' => '427','name' => 'নীলফামারী সদর','district_id' => '56'),
            array('id' => '428','name' => 'সাদুল্লাপুর','district_id' => '57'),
            array('id' => '429','name' => 'গাইবান্ধা সদর','district_id' => '57'),
            array('id' => '430','name' => 'পলাশবাড়ী','district_id' => '57'),
            array('id' => '431','name' => 'সাঘাটা','district_id' => '57'),
            array('id' => '432','name' => 'গোবিন্দগঞ্জ','district_id' => '57'),
            array('id' => '433','name' => 'সুন্দরগঞ্জ','district_id' => '57'),
            array('id' => '434','name' => 'ফুলছড়ি','district_id' => '57'),
            array('id' => '435','name' => 'ঠাকুরগাঁও সদর','district_id' => '58'),
            array('id' => '436','name' => 'পীরগঞ্জ','district_id' => '58'),
            array('id' => '437','name' => 'রাণীশংকৈল','district_id' => '58'),
            array('id' => '438','name' => 'হরিপুর','district_id' => '58'),
            array('id' => '439','name' => 'বালিয়াডাঙ্গী','district_id' => '58'),
            array('id' => '440','name' => 'রংপুর সদর','district_id' => '59'),
            array('id' => '441','name' => 'গংগাচড়া','district_id' => '59'),
            array('id' => '442','name' => 'তারাগঞ্জ','district_id' => '59'),
            array('id' => '443','name' => 'বদরগঞ্জ','district_id' => '59'),
            array('id' => '444','name' => 'মিঠাপুকুর','district_id' => '59'),
            array('id' => '445','name' => 'পীরগঞ্জ','district_id' => '59'),
            array('id' => '446','name' => 'কাউনিয়া','district_id' => '59'),
            array('id' => '447','name' => 'পীরগাছা','district_id' => '59'),
            array('id' => '448','name' => 'কুড়িগ্রাম সদর','district_id' => '60'),
            array('id' => '449','name' => 'নাগেশ্বরী','district_id' => '60'),
            array('id' => '450','name' => 'ভুরুঙ্গামারী','district_id' => '60'),
            array('id' => '451','name' => 'ফুলবাড়ী','district_id' => '60'),
            array('id' => '452','name' => 'রাজারহাট','district_id' => '60'),
            array('id' => '453','name' => 'উলিপুর','district_id' => '60'),
            array('id' => '454','name' => 'চিলমারী','district_id' => '60'),
            array('id' => '455','name' => 'রৌমারী','district_id' => '60'),
            array('id' => '456','name' => 'চর রাজিবপুর','district_id' => '60'),
            array('id' => '457','name' => 'শেরপুর সদর','district_id' => '61'),
            array('id' => '458','name' => 'নালিতাবাড়ী','district_id' => '61'),
            array('id' => '459','name' => 'শ্রীবরদী','district_id' => '61'),
            array('id' => '460','name' => 'নকলা','district_id' => '61'),
            array('id' => '461','name' => 'ঝিনাইগাতী','district_id' => '61'),
            array('id' => '462','name' => 'ফুলবাড়ীয়া','district_id' => '62'),
            array('id' => '463','name' => 'ত্রিশাল','district_id' => '62'),
            array('id' => '464','name' => 'ভালুকা','district_id' => '62'),
            array('id' => '465','name' => 'মুক্তাগাছা','district_id' => '62'),
            array('id' => '466','name' => 'ময়মনসিংহ সদর','district_id' => '62'),
            array('id' => '467','name' => 'ধোবাউড়া','district_id' => '62'),
            array('id' => '468','name' => 'ফুলপুর','district_id' => '62'),
            array('id' => '469','name' => 'হালুয়াঘাট','district_id' => '62'),
            array('id' => '470','name' => 'গৌরীপুর','district_id' => '62'),
            array('id' => '471','name' => 'গফরগাঁও','district_id' => '62'),
            array('id' => '472','name' => 'ঈশ্বরগঞ্জ','district_id' => '62'),
            array('id' => '473','name' => 'নান্দাইল','district_id' => '62'),
            array('id' => '474','name' => 'তারাকান্দা','district_id' => '62'),
            array('id' => '475','name' => 'জামালপুর সদর','district_id' => '63'),
            array('id' => '476','name' => 'মেলান্দহ','district_id' => '63'),
            array('id' => '477','name' => 'ইসলামপুর','district_id' => '63'),
            array('id' => '478','name' => 'দেওয়ানগঞ্জ','district_id' => '63'),
            array('id' => '479','name' => 'সরিষাবাড়ী','district_id' => '63'),
            array('id' => '480','name' => 'মাদারগঞ্জ','district_id' => '63'),
            array('id' => '481','name' => 'বকশীগঞ্জ','district_id' => '63'),
            array('id' => '482','name' => 'বারহাট্টা','district_id' => '64'),
            array('id' => '483','name' => 'দুর্গাপুর','district_id' => '64'),
            array('id' => '484','name' => 'কেন্দুয়া','district_id' => '64'),
            array('id' => '485','name' => 'আটপাড়া','district_id' => '64'),
            array('id' => '486','name' => 'মদন','district_id' => '64'),
            array('id' => '487','name' => 'খালিয়াজুরী','district_id' => '64'),
            array('id' => '488','name' => 'কলমাকান্দা','district_id' => '64'),
            array('id' => '489','name' => 'মোহনগঞ্জ','district_id' => '64'),
            array('id' => '490','name' => 'পূর্বধলা','district_id' => '64'),
            array('id' => '491','name' => 'নেত্রকোণা সদর','district_id' => '64')
          );


        foreach($divisions as $div){


            DB::table('divisions')->insert([
                'id' => $div['id'],
                'name' => $div['name']
            ]);

        }


        foreach($districts as $dis){


            DB::table('districts')->insert([
                'id' => $dis['id'],
                'name' => $dis['name'],
                'division_id' => $dis['division_id'],
            ]);

        }


        foreach($cities as $city){

            DB::table('cities')->insert([
                'id' => $city['id'],
                'name' => $city['name'],
                'district_id' => $city['district_id'],
            ]);

        }
    }
}
